services:
  moodleapp:
    image: oluwaseuna/runmoodle:1.0
    container_name: moodleapp
    expose:
      - "80"  
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - moodledb

  moodledb:
    image: mysql:8.4.5
    container_name: clouddb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - clouddbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:8081"
    environment:
      PMA_HOST: clouddb
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - moodledb

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - moodleapp
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/html:/var/www/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/html
      -d putme.run.edu.ng
      --email ict@run.edu.ng
      --agree-tos --non-interactive"

volumes:
  clouddbdata:
  moodledata: